App.EndPoint.UI.MVC/Models/ErrorViewModel.cs
namespace App.EndPoint.UI.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

App.EndPoint.UI.MVC/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace App.EndPoint.UI.MVC.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Emai { get; set; }
        [Required]
        public string Password { get; set; }

        public bool IsAdmin { get; set; } = false;
    }
}

App.EndPoint.UI.MVC/Controllers/AdminController.cs
using App.Core;
using App.Domain.Core.AdminEntity.Contracts;
using App.Domain.Core.BookEntity.Contracts;
using App.Domain.Core.BookEntity.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace App.EndPoint.UI.MVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IBookService _bookSrevice;
        public AdminController(IAdminService adminService, IBookService bookService)
        {
            _adminService = adminService;
            _bookSrevice = bookService;
        }


        public IActionResult Index()
        {
            var AllBooks = _bookSrevice.GetAll();
            return View(AllBooks);
        }


        public IActionResult BookDetails(int id)
        {
            var targetBook = _bookSrevice.GetById(id);
            return View(targetBook);
        }


        [HttpGet]
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBook(BookDTO bookModel)
        {
            _adminService.AddNewBook(bookModel);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteBook(int id)
        {
            _adminService.RemoveBook(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult EditBook(int id)
        {
            var targetBook = _bookSrevice.GetById(id);
            return View(targetBook);
        }

        [HttpPost]
        public IActionResult EditBook(Book book)
        {

            return RedirectToAction("Index");
        }
    }
}

App.EndPoint.UI.MVC/Controllers/AuthenticationController.cs
using App.Domain.Core.AdminEntity.Contracts;
using App.Domain.Core.CustomerEntity.Contracts;
using App.EndPoint.UI.MVC.Models;
using App.Infra.DataBase.MemoryDataBase;
using Microsoft.AspNetCore.Mvc;

namespace App.EndPoint.UI.MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly ICustomerService _customerService;

        public AuthenticationController(IAdminService adminService, ICustomerService customerService)
        {
            _adminService = adminService;
            _customerService = customerService;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.IsAdmin)
            {
                var admin = _adminService.CheckLogin(model.Emai, model.Password);
                if (admin != null)
                {
                    MemoryDataBase.ActiveAdmin = admin;
                    ViewData["successLogin"] = "access Level Admin";
                    return RedirectToAction("Index", "Admin");
                }
            }

            var customer = _customerService.CheckLogin(model.Emai, model.Password);
            if (customer != null)
            {
                MemoryDataBase.ActiveCustomer = customer;
                ViewData["successLogin"] = "access level Customer";
                return RedirectToAction("Index", "Customer");
            }

            ViewData["failedLogin"] = "account not found";
            return View(model);
        }

        public IActionResult Logout()
        {
            return RedirectToAction("Login");
        }
    }
}

App.EndPoint.UI.MVC/Controllers/CustomerController.cs
using App.Domain.Core.BookEntity.Contracts;
using App.Domain.Core.CustomerEntity.Contracts;
using App.Domain.Services.BookEntity;
using App.Infra.DataBase.MemoryDataBase;
using Microsoft.AspNetCore.Mvc;

namespace App.EndPoint.UI.MVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IBookService _bookSrevice;
        public CustomerController(ICustomerService customerService, IBookService bookService)
        {
            _bookSrevice = bookService;
            _customerService = customerService;
        }


        public IActionResult Index()
        {
            var allBooks = _bookSrevice.NoneBorrowedBooks();
            return View(allBooks);
        }

        [HttpGet]
        public IActionResult BookDetails(int id)
        {
            var targetBook = _bookSrevice.GetById(id);
            return View(targetBook);
        }


        [HttpGet]
        public IActionResult BorrowBook(int id)
        {
            _customerService.BorrowBook(id, MemoryDataBase.ActiveCustomer.Id);
            return RedirectToAction("CustomerBooks");
        }

        public IActionResult CustomerBooks()
        {
            var books = _customerService.CustomerBooks(MemoryDataBase.ActiveCustomer.Id);
            return View(books);
        }

        public IActionResult ReturnBook(int id)
        {
            _customerService.ReturnBook(id, MemoryDataBase.ActiveCustomer.Id);
            return RedirectToAction("CustomerBooks");
        }
    }
}

App.EndPoint.UI.MVC/Controllers/HomeController.cs
using App.EndPoint.UI.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.EndPoint.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App.EndPoint.UI.MVC/Views/Admin/AddBook.cshtml
@using App.Domain.Core.BookEntity.DTOs
@model BookDTO

@{
    ViewData["Title"] = "Add Book Page";
    Layout = "_AdminLayout";
}


<div class="container  col-lg-5">
    <form asp-action="AddBook" method="post">
        <label class="form-label" asp-for="@Model.Title"></label>
        <input type="text" class="form-control" asp-for="@Model.Title" />
        <label class="form-label" asp-for="@Model.AuthorName"></label>
        <input type="text" class="form-control" asp-for="@Model.AuthorName" />
        <label class="form-label" asp-for="@Model.Price"></label>
        <input type="number" class="form-control" asp-for="@Model.Price" />
        <div class=" my-3 d-grid gap-2">
            <input type="submit" class="btn btn-primary" value="submit" />
        </div>
    </form>
</div>

App.EndPoint.UI.MVC/Views/Admin/BookDetails.cshtml
@using App.Core
@model Book

@{
    ViewData["Title"] = "Book Details";
    Layout = "_AdminLayout";
}

<div class="container col-lg-5">
    <h2>جزئیات کتاب</h2>
</div>

<table class="table table-responsive">
    <thead>
        <tr>
            <th scope="row">عنوان</th>
            <th scope="row">نام نویسنده</th>
            <th scope="row">قیمت</th>
            <th scope="row">قرض گرفته شده</th>
            <th scope="row">نام مشتری</th>
            <th scope="row">عملیات</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        <tr>
            <td class="col">@Model.Title</td>
            <td class="col">@Model.AuthorName</td>
            <td class="col">@Model.Price</td>
            <td class="col">@Model.IsBorrowd</td>
            <td class="col">@if(Model.Customer != null){@Model.Customer.FirstName  @Model.Customer.LastName}</td>
            <td class="col">
                <a class="btn btn-sm btn-outline-warning" asp-action="EditBook" asp-route-id="@Model.Id">ویرایش</a>
                <a class="btn btn-sm btn-outline-danger" asp-action="DeleteBook" asp-route-id="@Model.Id">حذف</a>
            </td>
        </tr>
    </tbody>
</table>

App.EndPoint.UI.MVC/Views/Admin/EditBook.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

App.EndPoint.UI.MVC/Views/Admin/Index.cshtml
@using App.Domain.Core.BookEntity.DTOs
@model List<BookDTO>

@{
    ViewData["Title"] = "All Books";
    Layout = "_AdminLayout";
}

<div class="container col-lg-4">
    @if (ViewData["successLogin"] != null)
    {
        <div class="text-center" role="alert">
            <span class="text-success">@ViewData["successLogin"].ToString()</span>
        </div>
    }
</div>

<div class="container col-5 mb-5">
    <div class="border-bottom mx-auto text-center">
        <h2>کتاب ها</h2>
    </div>
</div>

<div class="container col-lg-6">
    <table class="table table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th scope="col">عنوان</th>
                <th scope="col">نویسنده</th>
                <th scope="col">قیمت</th>
                <th scope="col">عملیات</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.AuthorName</td>
                    <td>@book.Price</td>
                    <td>
                        <a class="btn btn-sm btn-outline-success" asp-action="BookDetails" asp-route-id="@book.Id">مشاهده بیشتر</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

App.EndPoint.UI.MVC/Views/Authentication/Login.cshtml
@model LoginViewModel

<div class="container col-lg-4">
    <form asp-action="Login" method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3">
            <input class="form-control" asp-for="@Model.Emai" type="email" placeholder="آدرس ایمیل" data-sb-validations="required,email" />
        </div>
        <div class="mb-3">
            <input class="form-control" asp-for="@Model.Password" type="password" placeholder="رمز عبور" data-sb-validations="required" />
        </div>
        <div class="mb-3">
            <span>برای ثبت نام <a asp-action="Register">کلیک</a> کنید</span>
        </div>
        <div class="mb-3">
            <input type="checkbox" asp-for="@Model.IsAdmin" />
            <label class="form-check-label">ادمین هستم</label>
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-primary" type="submit">تایید</button>
        </div>
    </form>
</div>

App.EndPoint.UI.MVC/Views/Customer/BookDetails.cshtml
@using App.Core
@model Book

@{
    ViewData["Title"] = "Book Details";
    Layout = "_CustomerLayout";
}

<div class="container col-lg-5">
    <h2>جزئیات کتاب</h2>
</div>

<table class="table table-responsive">
    <thead>
        <tr>
            <th scope="row">عنوان</th>
            <th scope="row">نام نویسنده</th>
            <th scope="row">قیمت</th>
            <th scope="row">عملیات</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        <tr>
            <td class="col">@Model.Title</td>
            <td class="col">@Model.AuthorName</td>
            <td class="col">@Model.Price</td>
            <td class="col">
                <a class="btn btn-sm btn-outline-primary" asp-action="BorrowBook" asp-route-id="@Model.Id">قرض گرفتن</a>
            </td>
        </tr>
    </tbody>
</table>

App.EndPoint.UI.MVC/Views/Customer/CustomerBooks.cshtml
@using App.Core
@using App.Domain.Core.BookEntity.DTOs
@model List<Book>

@{
    ViewData["Title"] = "Customer Books";
    Layout = "_CustomerLayout";
}

<div class="container col-5 mb-5">
    <div class="border-bottom mx-auto text-center">
        <h2>کتاب های شما</h2>
    </div>
</div>

<div class="container col-lg-6">
    <table class="table table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th scope="col">عنوان</th>
                <th scope="col">نویسنده</th>
                <th scope="col">قیمت</th>
                <th scope="col">عملیات</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.AuthorName</td>
                    <td>@book.Price</td>
                    <td>
                        <a class="btn btn-sm btn-outline-warning" asp-action="ReturnBook" asp-route-id="@book.Id"> بازگرداندن</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

App.EndPoint.UI.MVC/Views/Customer/Index.cshtml
@using App.Core
@using App.Domain.Core.BookEntity.DTOs
@model List<Book>

@{
    ViewData["Title"] = "All Books";
    Layout = "_CustomerLayout";
}

<div class="container col-lg-4">
    @if (ViewData["successLogin"] != null)
    {
        <div class="text-center" role="alert">
            <span class="text-success">@ViewData["successLogin"].ToString()</span>
        </div>
    }
</div>

<div class="container col-5 mb-5">
    <div class="border-bottom mx-auto text-center">
        <h2>کتاب ها</h2>
    </div>
</div>

<div class="container col-lg-6">
    <table class="table table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th scope="col">عنوان</th>
                <th scope="col">نویسنده</th>
                <th scope="col">قیمت</th>
                <th scope="col">عملیات</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.AuthorName</td>
                    <td>@book.Price</td>
                    <td>
                        <a class="btn btn-sm btn-outline-success" asp-action="BookDetails" asp-route-id="@book.Id">مشاهده بیشتر</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

App.EndPoint.UI.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

App.EndPoint.UI.MVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.EndPoint.UI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AddBook">Add Book</a>
                        </li>
                    </ul>
                    <a class="btn btn-sm btn-danger" asp-controller="Authentication" asp-action="Logout">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

App.EndPoint.UI.MVC/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Customer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.EndPoint.UI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="CustomerBooks">My Books</a>
                        </li>
                    </ul>
                    <a class="btn btn-sm btn-danger" asp-controller="Authentication" asp-action="Logout">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

App.EndPoint.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App.EndPoint.UI.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.EndPoint.UI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <a class="btn btn-sm btn-primary" asp-action="Login" asp-controller="Authentication">Login</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>